name: Playwright Tests
on:
  deployment_status:
jobs:
  test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' 
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
      
      - name: Echo github obj
        run: echo ${{ toJson(github) }}